export default TarotsCollection={
    "0": require("../assets/tarots/00.jpg"),
    "1": require("../assets/tarots/01.jpg"),
    "2": require("../assets/tarots/02.jpg"),
    "3": require("../assets/tarots/03.jpg"),
    "4": require("../assets/tarots/04.jpg"),
    "5": require("../assets/tarots/05.jpg"),
    "6": require("../assets/tarots/06.jpg"),
    "7": require("../assets/tarots/07.jpg"),
    "8": require("../assets/tarots/08.jpg"),
    "9": require("../assets/tarots/09.jpg"),
    "10": require("../assets/tarots/10.jpg"),
    "11": require("../assets/tarots/11.jpg"),
    "12": require("../assets/tarots/12.jpg"),
    "13": require("../assets/tarots/13.jpg"),
    "14": require("../assets/tarots/14.jpg"),
    "15": require("../assets/tarots/15.jpg"),
    "16": require("../assets/tarots/16.jpg"),
    "17": require("../assets/tarots/17.jpg"),
    "18": require("../assets/tarots/18.jpg"),
    "19": require("../assets/tarots/19.jpg"),
    "20": require("../assets/tarots/20.jpg"),
    "21": require("../assets/tarots/21.jpg")
}